name: Build & Deploy

on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'release/**'

env: 
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  
      - name: Create Github Release and Tag
        if: github.repository_owner == 'Authress' && github.ref != 'refs/heads/main' && github.event_name == 'push'
        run: |
          git tag ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER
          git push origin ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER